version: '3'

services:
  node:
    image: node:20-alpine
    ports:
      - '3000:3000'
    volumes:
      - ../app/personal-website:/srv/react-docker
    working_dir: /srv/react-docker
    command: 'npm start'